### ISSUE TITLE
Why does the error appear in this manner when I try to use the `tablex` function?

### ISSUE THREAD

**Issue by linhduongtuan** [PgBiel/typst-tablex#18]
Hi @PgBiel,
I am currently in the process of reimplementing this repository, which can be found at https://github.com/howardlau1999/sysu-thesis-typst, and I am trying to include my tables using `tablex`. However, I am encountering an error similar to the one depicted in the attached image.
Could you please provide an explanation or assist me in resolving this bug?

![Untitled](https://github.com/PgBiel/typst-tablex/assets/22388092/9a90709e-f36f-44cd-9c5a-ffbfeba8384f)

**Comment by PgBiel** [comment]
This error is not related to tablex. The `text` field is only available on `#text` elements. So, for example, it is available on `#[Hello world]`, since that piece of content is just some simple text, so it is internally converted (by the Typst compiler) to a single `text` element. However, `#[*Hello*]` would be a `strong` element instead (for bold), while `#[*Hello* world]` would be a sequence element, since it contains more than one kind of element inside (a `strong` followed by `text`). So, if your heading is simple and just contains text, `heading.body.text` will work; however, if it contains anything more complicated than that, you will need to know which kind of content your heading contains (e.g. use `.children` for a sequence, to get access to its inner elements; `.body` if it's another heading or something; etc.). There is, unfortunately, no universal way to convert any kind of element to a string yet. Hope this clears it up!

For further such questions, I recommend checking out either Typst's GitHub Discussions (https://github.com/typst/typst/discussions) or Typst's Discord server (check https://typst.app for a link at the top of the page). You will likely be able to get better and faster support there. :wink:

**Comment by linhduongtuan** [comment]
@PgBiel, I appreciate you taking the time to explain the details

**Comment by linhduongtuan** [comment]
@PgBiel 
Well, I think Typst has a bug somewhere. Now I can put my tables inside my context under heading levels, as well as can put them without headings separately.

**Comment by PgBiel** [comment]
> If you are pleased, could you answer my question about how to remove a legend and counting for a table inside the `#figure` function? Of course I can use `#grid` function instead of the nested functions `#figure(table...)`.

You can either remove the table from the figure, or disable the caption (not specify `caption:`).

**Comment by linhduongtuan** [comment]
I really appreciate your help.
