### ISSUE TITLE
Formatting breaks after typst update to 0.7.0

### ISSUE THREAD

**Issue by raphael-episub** [PgBiel/typst-tablex#39]
Placement of elements in document has broken with typst update to 0.7.0

**Comment by raphael-episub** [comment]
Some (rect) elements on the document were being rendered without width. I added and specified width and this fixed the issue.

**Comment by PgBiel** [comment]
Alright! Feel free to reopen if you find this issue again.

**Comment by PgBiel** [comment]
I'm reopening since this seems to be related to #44. I pushed a fix to main with commit https://github.com/PgBiel/typst-tablex/commit/f00b91c7d9383ebd194fb9e36ee5999339c38891 which might fix your issue (you wouldn't have to specify the block's width anymore). Feel free to test the latest code in the main branch to see if that solves it for you. Thanks!

**Comment by raphael-episub** [comment]
Thanks - sounds good.
