### ISSUE TITLE
Column sizes with mixed fractional and auto sizes don't fit the page

### ISSUE THREAD

**Issue by manveru** [PgBiel/typst-tablex#78]
```typ
#import "@preview/tablex:0.0.6": tablex, cellx

#tablex(
  columns: (1fr, 1fr, auto, auto, auto),
  [a], [b], [c], [d], [e],
  cellx(colspan: 5)[#lorem(5)],
  [a], [b], [c], [d], [e],
  cellx(colspan: 2)[#lorem(10)], none, none, none,
  [a], [b], [c], [d], [e],
  cellx(colspan: 3)[#lorem(15)], none, none,
)
```

Here's a rendered version of the difference the last row makes:

![rendered](https://github.com/PgBiel/typst-tablex/assets/3507/ed55f13a-8454-45c6-8a5f-63653141ef44)

It seems like some combination of longer text with automatic sizing and fractional scaling may cause that, but I can't really figure out the logic behind this.

**Comment by PgBiel** [comment]
Related: #56

**Comment by PgBiel** [comment]
I believe this happens because `auto` columns are calculated before `fr` columns. As such, the last lorem paragraph expands the most it can, causing the `auto` column to take all available space, leaving 0 space for the `1fr` columns. I'd like to improve the handling of `1fr` columns in such cases, but this is complicated because, technical limitations aside, I'm not sure what the expected behavior should even be! :joy:

I guess one could consider splitting evenly between `auto` and `1fr` in such cases, but that'll need further thought.

**Comment by PgBiel** [comment]
Thanks for the input. I believe your ideas are in the right direction.

I've found that tabularray[^1] has an option which would be the equivalent in tablex of having colspans not affect the sizes of auto columns at all (or rowspans not affect the sizes of auto rows). With such an option, you'd force colspans to fit into existing columns instead of causing them to expand, which would solve your problem, as the `auto` column it spans wouldn't expand unnecessarily. Of course, however, the colspan would have less space available, but that's a tradeoff one must consider. You'd choose what looks best in the end.

That could thus be added to tablex in an attempt to alleviate this kind of problem if needed.

[^1]: Starting at p. 27 of tabularray docs (`hspan` etc. options): https://mirrors.ctan.org/macros/latex/contrib/tabularray/tabularray.pdf

**Comment by PgBiel** [comment]
You may now use `fit-spans: (x: true)` to solve your problem. It causes auto columns to ignore colspans:

```typ
#tablex(
    columns: (1fr, 1fr, auto, auto, auto),
    fit-spans: (x: true),
    [a], [b], [c], [d], [e],
    cellx(colspan: 5)[#lorem(5)],
    [a], [b], [c], [d], [e],
    cellx(colspan: 2)[#lorem(10)], none, none, none,
    [a], [b], [c], [d], [e],
    cellx(colspan: 3)[#lorem(15)], none, none,
)
```

![image](https://github.com/PgBiel/typst-tablex/assets/9021226/7fcc8ccf-c5d0-410e-b883-7bbbe8841d23)

Keeping this open as I might make tablex smarter in this regard in the future (specifically if the cell spans all fractional columns available).

**Comment by PgBiel** [comment]
This particular case (of a colspan over all fractional columns) is now automatically handled. You may opt into having auto columns ignore the sizes of colspans with `fit-spans: (x: true)`.
